/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supervision;

/**
 *
 * @author Mignot
 */
public class Fenetre extends java.awt.Frame {
    
    private final String TITRE = "Supervision des Livraisons Itinérantes Planifiés";

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        this.setTitle(TITRE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGauche = new javax.swing.JPanel();
        jPanelBoutonsGen = new javax.swing.JPanel();
        jButtonUndo = new javax.swing.JButton();
        jButtonDo = new javax.swing.JButton();
        jComboBoxZone = new javax.swing.JComboBox();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jPanelPlan = new javax.swing.JPanel();
        jPanelEditionLivraison = new javax.swing.JPanel();
        jLabelEdLivTitre = new javax.swing.JLabel();
        jButtonSupprimerLiv = new javax.swing.JButton();
        jLabelAddLivCurr = new javax.swing.JLabel();
        jButtonValiderLiv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelLivCurr = new javax.swing.JLabel();
        jLabelLivPrec = new javax.swing.JLabel();
        jLabelAddLivPrec = new javax.swing.JLabel();
        jLabelLivSuiv = new javax.swing.JLabel();
        jLabelAddLivSuiv = new javax.swing.JLabel();
        jPanelDroite = new javax.swing.JPanel();
        jLabelTitreTournee = new javax.swing.JLabel();
        jPanelTournee = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonGenTourn = new javax.swing.JButton();
        jButtonFinal = new javax.swing.JButton();
        jLabelPartieInvisible = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelGauche.setBackground(new java.awt.Color(102, 0, 153));

        jPanelBoutonsGen.setBackground(new java.awt.Color(255, 204, 102));
        jPanelBoutonsGen.setLayout(new java.awt.GridLayout(1, 0));

        jButtonUndo.setText("<-");
        jPanelBoutonsGen.add(jButtonUndo);

        jButtonDo.setText("->");
        jPanelBoutonsGen.add(jButtonDo);

        jComboBoxZone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxZone.setToolTipText("Changer de zone");
        jPanelBoutonsGen.add(jComboBoxZone);

        jFormattedTextFieldDate.setText("Date de la tournée");
        jFormattedTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDateActionPerformed(evt);
            }
        });
        jPanelBoutonsGen.add(jFormattedTextFieldDate);

        jPanelPlan.setBackground(new java.awt.Color(102, 102, 255));

        jPanelEditionLivraison.setBackground(new java.awt.Color(0, 153, 153));

        jLabelEdLivTitre.setText("Edition de livraison");

        jButtonSupprimerLiv.setText("Supprimer");

        jLabelAddLivCurr.setText("Aucune livraison sélectionnée");

        jButtonValiderLiv.setText("Valider");

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabelLivCurr.setText("Adresse de livraison :");

        jLabelLivPrec.setText("Livraison précedente :");

        jLabelAddLivPrec.setText("Aucune livraison sélectionnée");

        jLabelLivSuiv.setText("Livraison suivante :");

        jLabelAddLivSuiv.setText("Aucune livraison sélectionnée");

        javax.swing.GroupLayout jPanelEditionLivraisonLayout = new javax.swing.GroupLayout(jPanelEditionLivraison);
        jPanelEditionLivraison.setLayout(jPanelEditionLivraisonLayout);
        jPanelEditionLivraisonLayout.setHorizontalGroup(
            jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEdLivTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addComponent(jLabelLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelAddLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addComponent(jLabelLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelAddLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addComponent(jLabelLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelAddLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButtonSupprimerLiv)
                .addGap(39, 39, 39)
                .addComponent(jButtonValiderLiv))
        );
        jPanelEditionLivraisonLayout.setVerticalGroup(
            jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addComponent(jLabelEdLivTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSupprimerLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValiderLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelGaucheLayout = new javax.swing.GroupLayout(jPanelGauche);
        jPanelGauche.setLayout(jPanelGaucheLayout);
        jPanelGaucheLayout.setHorizontalGroup(
            jPanelGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGaucheLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBoutonsGen, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEditionLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelGaucheLayout.setVerticalGroup(
            jPanelGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGaucheLayout.createSequentialGroup()
                .addComponent(jPanelBoutonsGen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelEditionLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelDroite.setBackground(new java.awt.Color(51, 255, 51));
        jPanelDroite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitreTournee.setText("Tournée");
        jPanelDroite.add(jLabelTitreTournee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 220, 30));

        jPanelTournee.setBackground(new java.awt.Color(255, 0, 0));
        jPanelTournee.add(jPanel1);

        jPanelDroite.add(jPanelTournee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 380));

        jButtonGenTourn.setText("Générer tournée");
        jPanelDroite.add(jButtonGenTourn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 50));

        jButtonFinal.setText("Finaliser tournée");
        jPanelDroite.add(jButtonFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 50));

        jLabelPartieInvisible.setText("Inexplicablemet, cette partie de la fenêtre ne s'affiche pas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPartieInvisible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPartieInvisible, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDroite, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jFormattedTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDo;
    private javax.swing.JButton jButtonFinal;
    private javax.swing.JButton jButtonGenTourn;
    private javax.swing.JButton jButtonSupprimerLiv;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonValiderLiv;
    private javax.swing.JComboBox jComboBoxZone;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabelAddLivCurr;
    private javax.swing.JLabel jLabelAddLivPrec;
    private javax.swing.JLabel jLabelAddLivSuiv;
    private javax.swing.JLabel jLabelEdLivTitre;
    private javax.swing.JLabel jLabelLivCurr;
    private javax.swing.JLabel jLabelLivPrec;
    private javax.swing.JLabel jLabelLivSuiv;
    private javax.swing.JLabel jLabelPartieInvisible;
    private javax.swing.JLabel jLabelTitreTournee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBoutonsGen;
    private javax.swing.JPanel jPanelDroite;
    private javax.swing.JPanel jPanelEditionLivraison;
    private javax.swing.JPanel jPanelGauche;
    private javax.swing.JPanel jPanelPlan;
    private javax.swing.JPanel jPanelTournee;
    // End of variables declaration//GEN-END:variables
}
