/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supervision;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Menu;
import java.awt.MenuBar;
import java.awt.MenuItem;


/**
 *
 * @author Mignot
 */
public class Fenetre extends java.awt.Frame {
    
    private final String TITRE = "Supervision des Livraisons Itinérantes Planifiés";

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        this.setTitle(TITRE);
        creeMenu();
        
    }
    
	private void creeMenu(){
		// Creation de deux menus, chaque menu ayant plusieurs items
		// et association d'un ecouteur d'action a chacun de ces items

		Menu menuFichier = new Menu("Fichier");
		Menu menuEdition = new Menu("Edition");
		ActionListener a4 = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        };
		ajoutItem("Sauvegarder en XML", menuFichier, a4);
		ActionListener a5 = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        };
		ajoutItem("Ouvrir un fichier XML", menuFichier, a5);
                
		ActionListener a6 = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        };
		ajoutItem("Undo", menuEdition, a6);
                
		ActionListener a7 = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        };
		ajoutItem("Redo", menuEdition, a7);
		
		MenuBar barreDeMenu = new MenuBar();
        barreDeMenu.add(menuFichier);
        barreDeMenu.add(menuEdition);
        this.setMenuBar(barreDeMenu);
	}
	
	private void ajoutItem(String intitule, Menu menu, ActionListener a){
		MenuItem item = new MenuItem(intitule);
		menu.add(item);
		item.addActionListener(a);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGauche = new javax.swing.JPanel();
        jPanelBoutonsGen = new javax.swing.JPanel();
        jButtonUndo = new javax.swing.JButton();
        jButtonDo = new javax.swing.JButton();
        jComboBoxZone = new javax.swing.JComboBox();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jPanelPlan = new javax.swing.JPanel();
        jPanelEditionLivraison = new javax.swing.JPanel();
        jLabelEdLivTitre = new javax.swing.JLabel();
        jButtonSupprimerLiv = new javax.swing.JButton();
        jLabelAddLivCurr = new javax.swing.JLabel();
        jButtonValiderLiv = new javax.swing.JButton();
        jPanelHoraires = new javax.swing.JPanel();
        jLabelLivCurr = new javax.swing.JLabel();
        jLabelLivPrec = new javax.swing.JLabel();
        jLabelAddLivPrec = new javax.swing.JLabel();
        jLabelLivSuiv = new javax.swing.JLabel();
        jLabelAddLivSuiv = new javax.swing.JLabel();
        jPanelDroite = new javax.swing.JPanel();
        jLabelTitreTournee = new javax.swing.JLabel();
        jPanelTournee = new javax.swing.JPanel();
        jButtonGenTourn = new javax.swing.JButton();
        jButtonFinal = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelGauche.setBackground(new java.awt.Color(102, 0, 153));

        jPanelBoutonsGen.setBackground(new java.awt.Color(255, 204, 102));
        jPanelBoutonsGen.setLayout(new java.awt.GridLayout(1, 0));

        jButtonUndo.setText("<-");
        jPanelBoutonsGen.add(jButtonUndo);

        jButtonDo.setText("->");
        jPanelBoutonsGen.add(jButtonDo);

        jComboBoxZone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxZone.setToolTipText("Changer de zone");
        jPanelBoutonsGen.add(jComboBoxZone);

        jFormattedTextFieldDate.setText("Date de la tournée");
        jFormattedTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDateActionPerformed(evt);
            }
        });
        jPanelBoutonsGen.add(jFormattedTextFieldDate);

        jPanelPlan.setBackground(new java.awt.Color(102, 102, 255));

        jPanelEditionLivraison.setBackground(new java.awt.Color(0, 153, 153));

        jLabelEdLivTitre.setText("Edition de livraison");

        jButtonSupprimerLiv.setText("Supprimer");

        jLabelAddLivCurr.setText("Aucune livraison sélectionnée");

        jButtonValiderLiv.setText("Valider");

        jPanelHoraires.setBackground(new java.awt.Color(255, 255, 0));
        jPanelHoraires.setLayout(new java.awt.GridLayout(1, 0));

        jLabelLivCurr.setText("Adresse de livraison :");

        jLabelLivPrec.setText("Livraison précedente :");

        jLabelAddLivPrec.setText("Aucune livraison sélectionnée");

        jLabelLivSuiv.setText("Livraison suivante :");

        jLabelAddLivSuiv.setText("Aucune livraison sélectionnée");

        javax.swing.GroupLayout jPanelEditionLivraisonLayout = new javax.swing.GroupLayout(jPanelEditionLivraison);
        jPanelEditionLivraison.setLayout(jPanelEditionLivraisonLayout);
        jPanelEditionLivraisonLayout.setHorizontalGroup(
            jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEdLivTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                        .addComponent(jLabelLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelAddLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                        .addComponent(jLabelLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelAddLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                        .addComponent(jLabelLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelAddLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelHoraires, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButtonSupprimerLiv)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonValiderLiv)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEditionLivraisonLayout.setVerticalGroup(
            jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditionLivraisonLayout.createSequentialGroup()
                .addComponent(jLabelEdLivTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivCurr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLivSuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanelHoraires, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanelEditionLivraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSupprimerLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonValiderLiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGaucheLayout = new javax.swing.GroupLayout(jPanelGauche);
        jPanelGauche.setLayout(jPanelGaucheLayout);
        jPanelGaucheLayout.setHorizontalGroup(
            jPanelGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBoutonsGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEditionLivraison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelGaucheLayout.setVerticalGroup(
            jPanelGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGaucheLayout.createSequentialGroup()
                .addComponent(jPanelBoutonsGen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEditionLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDroite.setBackground(new java.awt.Color(51, 255, 51));

        jLabelTitreTournee.setText("Tournée");

        jPanelTournee.setBackground(new java.awt.Color(255, 0, 0));

        jButtonGenTourn.setText("Générer tournée");

        jButtonFinal.setText("Finaliser tournée");

        javax.swing.GroupLayout jPanelDroiteLayout = new javax.swing.GroupLayout(jPanelDroite);
        jPanelDroite.setLayout(jPanelDroiteLayout);
        jPanelDroiteLayout.setHorizontalGroup(
            jPanelDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitreTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelDroiteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenTourn)
                    .addComponent(jButtonFinal)))
        );
        jPanelDroiteLayout.setVerticalGroup(
            jPanelDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDroiteLayout.createSequentialGroup()
                .addComponent(jLabelTitreTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelTournee, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonGenTourn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDroite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelGauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jFormattedTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDo;
    private javax.swing.JButton jButtonFinal;
    private javax.swing.JButton jButtonGenTourn;
    private javax.swing.JButton jButtonSupprimerLiv;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonValiderLiv;
    private javax.swing.JComboBox jComboBoxZone;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabelAddLivCurr;
    private javax.swing.JLabel jLabelAddLivPrec;
    private javax.swing.JLabel jLabelAddLivSuiv;
    private javax.swing.JLabel jLabelEdLivTitre;
    private javax.swing.JLabel jLabelLivCurr;
    private javax.swing.JLabel jLabelLivPrec;
    private javax.swing.JLabel jLabelLivSuiv;
    private javax.swing.JLabel jLabelTitreTournee;
    private javax.swing.JPanel jPanelBoutonsGen;
    private javax.swing.JPanel jPanelDroite;
    private javax.swing.JPanel jPanelEditionLivraison;
    private javax.swing.JPanel jPanelGauche;
    private javax.swing.JPanel jPanelHoraires;
    private javax.swing.JPanel jPanelPlan;
    private javax.swing.JPanel jPanelTournee;
    // End of variables declaration//GEN-END:variables
}
