/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supervision;

/**
 *
 * @author Mignot
 */
public class Fenetre extends java.awt.Frame {
    
    private final String TITRE = "Supervision des Livraisons Itinérantes Planifiés";

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        this.setTitle(TITRE);
        jPanelGauche.setSize(this.getHeight(), this.getWidth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGauche = new javax.swing.JPanel();
        jPanelBoutonsGen = new javax.swing.JPanel();
        jButtonUndo = new javax.swing.JButton();
        jButtonDo = new javax.swing.JButton();
        jComboBoxZone = new javax.swing.JComboBox();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jPanelPlan = new javax.swing.JPanel();
        jPanelEditionLivraison = new javax.swing.JPanel();
        jLabelEdLivTitre = new javax.swing.JLabel();
        jButtonSupprimerLiv = new javax.swing.JButton();
        jLabelAddLivCurr = new javax.swing.JLabel();
        jButtonValiderLiv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelLivCurr = new javax.swing.JLabel();
        jLabelLivPrec = new javax.swing.JLabel();
        jLabelAddLivPrec = new javax.swing.JLabel();
        jLabelLivSuiv = new javax.swing.JLabel();
        jLabelAddLivSuiv = new javax.swing.JLabel();
        jPanelDroite = new javax.swing.JPanel();
        jLabelTitreTournee = new javax.swing.JLabel();
        jPanelTournee = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPartieInvisible = new javax.swing.JLabel();
        jButtonGenTourn = new javax.swing.JButton();
        jButtonFinal = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGauche.setBackground(new java.awt.Color(102, 0, 153));
        jPanelGauche.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBoutonsGen.setBackground(new java.awt.Color(255, 204, 102));
        jPanelBoutonsGen.setLayout(new java.awt.GridLayout(1, 0));

        jButtonUndo.setText("<-");
        jPanelBoutonsGen.add(jButtonUndo);

        jButtonDo.setText("->");
        jPanelBoutonsGen.add(jButtonDo);

        jComboBoxZone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxZone.setToolTipText("Changer de zone");
        jPanelBoutonsGen.add(jComboBoxZone);

        jFormattedTextFieldDate.setText("Date de la tournée");
        jFormattedTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDateActionPerformed(evt);
            }
        });
        jPanelBoutonsGen.add(jFormattedTextFieldDate);

        jPanelGauche.add(jPanelBoutonsGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 30));

        jPanelPlan.setBackground(new java.awt.Color(102, 102, 255));
        jPanelGauche.add(jPanelPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, 380));

        jPanelEditionLivraison.setBackground(new java.awt.Color(0, 153, 153));
        jPanelEditionLivraison.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEdLivTitre.setText("Edition de livraison");
        jPanelEditionLivraison.add(jLabelEdLivTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        jButtonSupprimerLiv.setText("Supprimer");
        jPanelEditionLivraison.add(jButtonSupprimerLiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 183, -1, 30));

        jLabelAddLivCurr.setText("Aucune livraison sélectionnée");
        jPanelEditionLivraison.add(jLabelAddLivCurr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 320, 30));

        jButtonValiderLiv.setText("Valider");
        jPanelEditionLivraison.add(jButtonValiderLiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 183, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jPanelEditionLivraison.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 430, 60));

        jLabelLivCurr.setText("Adresse de livraison :");
        jPanelEditionLivraison.add(jLabelLivCurr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, 30));

        jLabelLivPrec.setText("Livraison précedente :");
        jPanelEditionLivraison.add(jLabelLivPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 30));

        jLabelAddLivPrec.setText("Aucune livraison sélectionnée");
        jPanelEditionLivraison.add(jLabelAddLivPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 320, 30));

        jLabelLivSuiv.setText("Livraison suivante :");
        jPanelEditionLivraison.add(jLabelLivSuiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 30));

        jLabelAddLivSuiv.setText("Aucune livraison sélectionnée");
        jPanelEditionLivraison.add(jLabelAddLivSuiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, 30));

        jPanelGauche.add(jPanelEditionLivraison, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 420, 220));

        add(jPanelGauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, 630));

        jPanelDroite.setBackground(new java.awt.Color(51, 255, 51));
        jPanelDroite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitreTournee.setText("Tournée");
        jPanelDroite.add(jLabelTitreTournee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 220, 30));

        jPanelTournee.setBackground(new java.awt.Color(255, 0, 0));

        jLabelPartieInvisible.setText("Inexplicablemet, cette partie de la fenêtre ne s'affiche pas");
        jPanel1.add(jLabelPartieInvisible);

        jPanelTournee.add(jPanel1);

        jPanelDroite.add(jPanelTournee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 380));

        jButtonGenTourn.setText("Générer tournée");
        jPanelDroite.add(jButtonGenTourn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 50));

        jButtonFinal.setText("Finaliser tournée");
        jPanelDroite.add(jButtonFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 50));

        add(jPanelDroite, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 220, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jFormattedTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDo;
    private javax.swing.JButton jButtonFinal;
    private javax.swing.JButton jButtonGenTourn;
    private javax.swing.JButton jButtonSupprimerLiv;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonValiderLiv;
    private javax.swing.JComboBox jComboBoxZone;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabelAddLivCurr;
    private javax.swing.JLabel jLabelAddLivPrec;
    private javax.swing.JLabel jLabelAddLivSuiv;
    private javax.swing.JLabel jLabelEdLivTitre;
    private javax.swing.JLabel jLabelLivCurr;
    private javax.swing.JLabel jLabelLivPrec;
    private javax.swing.JLabel jLabelLivSuiv;
    private javax.swing.JLabel jLabelPartieInvisible;
    private javax.swing.JLabel jLabelTitreTournee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBoutonsGen;
    private javax.swing.JPanel jPanelDroite;
    private javax.swing.JPanel jPanelEditionLivraison;
    private javax.swing.JPanel jPanelGauche;
    private javax.swing.JPanel jPanelPlan;
    private javax.swing.JPanel jPanelTournee;
    // End of variables declaration//GEN-END:variables
}
